A little more general backup script.

diff --git a/bin/backup_home b/bin/backup_home
--- a/bin/backup_home
+++ b/bin/backup_home
@@ -1,27 +1,34 @@
 #!/bin/bash
 
-if [[ "$1" == "" ]] ; then
-    BACKUP_DIR=/mnt/backup/$LOGNAME/home/backup
-else
-    # backup_home /mnt/tmp/kjell/backup/home
-    # places kjean part of /home/kjean in /mnt/tmp/kjell/backup/home.X/kjean
-    if [[ $1 =~ [^/]+/$ ]] ; then
-	echo "Backup dir ends with a '/', are you sure you want to do that?"
-	exit 1
-    fi
-    BACKUP_DIR=$1
+if [ $# != 2 ] ; then
+    echo "usage: $0 SOURCE DESTINATION" >&2
+    exit 1
 fi
 
-BACKUP_SOURCE_DIR=$HOME
+# $0 /home/foo /mnt/backup
+# copies contents of foo to /mnt/backup/home/foo.0 hardlinked from /mnt/backup/home/foo.1
+
+# Added a slash at the end of BACKUP_SOURCE to move the contents of the directory,
+# not the directory and its contents.
+BACKUP_SOURCE=$1/
+BACKUP_DEST=$2$1
+
 EXCLUDES=$HOME/.skel/rsync_excludes
 
 BACKUPS=8
-rm -rf $BACKUP_DIR.$BACKUPS
+rm -rf $BACKUP_DEST.$BACKUPS
 for (( i=$BACKUPS ; i > 0 ; i=i-1 )) ; do
-    mv $BACKUP_DIR.$(( $i-1 )) $BACKUP_DIR.$i
+    mv $BACKUP_DEST.$(( $i-1 )) $BACKUP_DEST.$i
 done
-mkdir -p $BACKUP_DIR.0
+mkdir -p $BACKUP_DEST
 
 rsync --archive --one-file-system --hard-links --human-readable --inplace \
     --numeric-ids --delete --delete-excluded --exclude-from=$EXCLUDES \
-    --link-dest=$BACKUP_DIR.1 $BACKUP_SOURCE_DIR $BACKUP_DIR.0
+    --link-dest=$BACKUP_DEST.1 $BACKUP_SOURCE $BACKUP_DEST
+ERR=$?
+if [ $ERR != 0 ] ; then
+    echo "rsync returned an error ($ERR), not moving directories." >&2
+    exit 1
+fi
+
+mv $BACKUP_DEST $BACKUP_DEST.0
